# Generated by Django 3.1 on 2020-08-16 08:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='专题名')),
            ],
            options={
                'verbose_name': '专题分类',
                'verbose_name_plural': '专题分类',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='文章名称')),
                ('body', mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='正文')),
                ('visiting', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='访问量')),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_post', to='tutorial.post', verbose_name='父亲文章')),
                ('prev_post', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_post', to='tutorial.post', verbose_name='前一篇文章')),
                ('topics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.topic', verbose_name='所属专题')),
            ],
            options={
                'verbose_name': '专题文章',
                'verbose_name_plural': '专题文章',
                'ordering': ['gmt_create'],
            },
        ),
    ]
