# Generated by Django 3.1 on 2020-08-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['gmt_create'], 'verbose_name': '内容', 'verbose_name_plural': '内容'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': '主题', 'verbose_name_plural': '主题'},
        ),
        migrations.AlterModelTable(
            name='post',
            table='wy_tutorial_post',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='wy_tutorial_topic',
        ),
    ]
