# Generated by Django 3.1 on 2020-08-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20200816_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='index',
            field=models.IntegerField(default=99, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=128, verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=128, verbose_name='主题'),
        ),
    ]
