# Generated by Django 3.1 on 2020-08-16 15:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='About 内容')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
                'db_table': 'wy_blog_About',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': '文章作者',
                'verbose_name_plural': '文章作者',
                'db_table': 'wy_blog_author',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='编号决定图片播放的顺序，图片不要多于5张', verbose_name='编号')),
                ('title', models.CharField(blank=True, help_text='标题可以为空', max_length=20, null=True, verbose_name='标题')),
                ('content', models.CharField(max_length=80, verbose_name='描述')),
                ('img_url', models.CharField(max_length=200, verbose_name='图片地址')),
                ('url', models.CharField(default='#', help_text='图片跳转的超链接，默认#表示不跳转', max_length=200, verbose_name='跳转链接')),
            ],
            options={
                'verbose_name': '图片轮播',
                'verbose_name_plural': '图片轮播',
                'db_table': 'wy_blog_carousel',
                'ordering': ['number', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=30, verbose_name='分类名称')),
                ('index', models.IntegerField(default=99, verbose_name='分类排序')),
                ('active', models.BooleanField(default=False, verbose_name='是否添加到菜单')),
                ('icon', models.CharField(default='fa fa-home', max_length=30, verbose_name='菜单图标')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'wy_blog_category',
            },
        ),
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('url', models.URLField(verbose_name='地址')),
                ('desc', models.TextField(max_length=250, verbose_name='描述')),
                ('image', models.URLField(default='https://image.3001.net/images/20190330/1553875722169.jpg', verbose_name='头像')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'db_table': 'wy_blog_friendlink',
                'ordering': ['create_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'wy_blog_tag',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='标题')),
                ('body', mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='正文')),
                ('digest', models.TextField(blank=True, null=True)),
                ('gmt_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('gmt_modified', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('view', models.BigIntegerField(default=0, verbose_name='阅读数')),
                ('author', models.CharField(default='anonymous', editable=False, max_length=128, verbose_name='作者')),
                ('cover', models.CharField(default='/static/default/code.jpg', max_length=200, verbose_name='文章封面')),
                ('status', models.SmallIntegerField(choices=[(0, '原创'), (1, '转发'), (2, '关注')], default=0, verbose_name='类型')),
                ('access_permissions', models.BooleanField(default=False, verbose_name='仅自己可见')),
                ('comment_permissions', models.BooleanField(default=False, verbose_name='禁止评论')),
                ('localized_img', models.BooleanField(default=False, verbose_name='下载外站图片到本地')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'wy_blog_article',
                'ordering': ['-gmt_create'],
            },
        ),
    ]
