# Generated by Django 3.1 on 2020-08-14 09:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文章分类')),
            ],
            options={
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标签')),
            ],
            options={
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='标题')),
                ('body', mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='正文')),
                ('digest', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, '原'), (1, '转'), (2, '顶')], default=0, verbose_name='类型')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('mod_date', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('view', models.BigIntegerField(default=0, verbose_name='阅读数')),
                ('author', models.CharField(default='anonymous', editable=False, max_length=128, verbose_name='作者')),
                ('picture', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片地址')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name_plural': '文章',
                'ordering': ['-publish'],
            },
        ),
    ]
